### ISSUE TITLE
Desperate for Help

### ISSUE THREAD

**Issue by mauritzgc** [TheGamer456YT/frick-discord-2fa#3]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: None
- Spicetify version: None
```

### 📝 Description

Good Day, please forgive my ignorance this is not a bug but a plea for help. How do I use this to get into my account. My phone is lost and I have no access to backup codes either. It might be a long shot but your assistance will be greatly appreciated.

**Comment by Derpitron** [comment]
frick-discord-2fa isn't a tool which can brute force into your account for you, it's just a random OTP code generator. If you want a working tool, you can check out my script here: https://github.com/hydino2085143/Discord-OTP-Forcer which uses this as a library. If you need help with anything, feel free to file an issue on my repo
