### ISSUE TITLE
BRO I REALLY NEED YOUR HELP . I ALSO GOT LOCKED OUT CAN U PLEASE HELP ME OUT

### ISSUE THREAD

**Issue by the-streetpilot** [TheGamer456YT/frick-discord-2fa#4]
### 📝 Provide a description of the new feature

i also set google authenticator .. but i uninstalled the app and when i reinstalled the app there was no old codes . i tried contactig discord support team many teams but they shit on me. please help me .. i really dont know how to brute force

**Comment by mauritzgc** [comment]
Go to this repository install python on your machine follow the instructions. Then once all is done open up main in the src folder and it will start generating codes for you after you sign in to discord. Ive been trying it for the last few days keeping fingers cross.

https://github.com/hydino2085143/Discord-OTP-Forcer

**Comment by Derpitron** [comment]
> Ive been trying it for the last few days keeping fingers cross.

Be careful when running it continuously, Discord might ban your account/IP for spamming the API. Use it sparingly, once every 15 minutes or so

**Comment by SpaghettDev** [comment]
As @mauritzgc said, use Discord-OTP-Forcer by Derpitron, this repo only has a random 2FA code generator, so to actually bruteforce your way into your account you'll need Discord-OTP-Forcer.
I should probably make it clear that this repo is just a code generator and not a bruteforcer.
