### ISSUE TITLE
Is this only can if i know the password?

### ISSUE THREAD

**Issue by farid31j** [TheGamer456YT/frick-discord-2fa#6]
Hello! i want to know is this codes only works if i know the password? i did try reset the password on my very old discord account that i forgot the password, but it says invalid

**Comment by Derpitron** [comment]
Hello,

This program requires an email/phone number **and** the password. There is no option in the program for doing password resets or managing them.

This program is only for discord accounts which have 2FA via Authenticator enabled, and the email and password are known.

**Comment by Derpitron** [comment]
Please read this:https://github.com/SpaghettDev/frick-discord-2fa/issues/7#issuecomment-1445925159

Also, my program is having a Password Reset feature to be added in soon. Check it out: https://github.com/Derpitron/Discord-OTP-Forcer/pull/15

**Comment by farid31j** [comment]
ahh okay! appreciate it, cause i want to log in my old account and i really forgot the password so i need to search some python coding that can work for resetting passsword and send the codes for resetting it.
