### ISSUE TITLE
ip ban chances? 

### ISSUE THREAD

**Issue by lukaa49** [TheGamer456YT/frick-discord-2fa#7]
how likely are you to get ip banned by discord for trying such, surely they don't allowed smth like this.
if the chances aren't too high I might go and try to do it.

**Comment by lukaa49** [comment]
and could an ip ban be avoided via VPN maybe?

**Comment by Derpitron** [comment]
1. From my experience, Discord is unlikely to IP ban you, unless you spam codes multiple times per minute. If you get ratelimited, wait around 10 minutes and retry, do NOT keep forcing it.
2. This program is not a full OTP brute forcer, it's only a library program, i.e not meant for end-users. If you want an actual tool for brute-forcing, try my program out: https://github.com/Derpitron/Discord-OTP-Forcer It includes rate limit detection/prevention and some other features.
